"""中文分词列:text_tokens,词法检索的前置条件

问题:0001 里 text_tsv 是 to_tsvector('simple', text) 生成的,而 simple 配置
      靠【空格】切词。中文没空格 → 整句变成一个 token。实测:
          to_tsvector('simple','地膜厚度应不小于0.010mm')
            → '地膜厚度应不小于0.010mm':1      ← 一整坨
          搜「地膜厚度」false / 「厚度」false / 「PBAT」false / 「0.010」false
      夹在中文里的英文和数字同样无法命中(与中文粘连成同一 token),
      0001 所建全文索引对中文语料实际不可用。

方案:Python 侧用 jieba 分好词写进 text_tokens,触发器改成从 text_tokens 生成 tsvector。
      为什么不在触发器里分词:触发器跑在 PG 进程里,调不到 Python 的 jieba。
      为什么不装 zhparser 扩展:要自己 build 镜像、升级 PG 就得重来、分词逻辑是黑盒。
      jieba 在 Python 侧能加领域词典("全生物降解地膜"不被切碎)、能写单元测试。

手工补的部分(Alembic 只 diff 表结构,不管触发器):触发器改造 + 回填提示。

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-20
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # 手工补:autogenerate 未生成此 import

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks",
        sa.Column(
            "text_tokens",
            sa.Text(),
            nullable=True,
            comment="jieba 分词后的词串(空格分隔),由 Python 侧写入;text_tsv 由触发器从它生成",
        ),
    )
    op.alter_column(
        "chunks",
        "text_tsv",
        existing_type=postgresql.TSVECTOR(),
        comment="全文检索向量,触发器从 text_tokens 生成(不是从 text —— simple 配置不分中文词)",
        existing_comment="全文检索向量,触发器自动维护。当前用 simple 配置(未做中文分词,技术债)",
        existing_nullable=True,
    )
    # ### end Alembic commands ###

    # ── 手工补:触发器改从 text_tokens 生成 ──
    #
    # 触发条件也变了:0001 是 UPDATE OF text,现在是 UPDATE OF text_tokens。
    # 因为分词是 Python 侧做的 —— text 变了不代表 tokens 已经重新算过。
    # 只有 tokens 写进来的那一刻,tsv 才该跟着变。
    op.execute(
        """
        CREATE OR REPLACE FUNCTION chunks_set_tsv() RETURNS trigger AS $$
        BEGIN
            NEW.text_tsv = to_tsvector('simple', COALESCE(NEW.text_tokens, ''));
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute("DROP TRIGGER IF EXISTS chunks_set_tsv_trigger ON chunks")
    op.execute(
        """
        CREATE TRIGGER chunks_set_tsv_trigger
            BEFORE INSERT OR UPDATE OF text_tokens ON chunks
            FOR EACH ROW EXECUTE FUNCTION chunks_set_tsv();
        """
    )

    # 已有的 26 万行 text_tokens 全是 NULL → tsv 也全是空的。
    # 回填要跑 jieba,那是 Python 的活,不在 migration 里做:
    #     uv run python scripts/backfill_tokens.py
    # (migration 只负责结构;数据迁移是独立的、可重跑的脚本 —— 26 万行的
    #  回填如果塞进 migration,中途挂了整个 migration 回滚,白跑)


def downgrade() -> None:
    # 手工补:触发器退回从 text 直接生成(即 0001 的行为)
    op.execute(
        """
        CREATE OR REPLACE FUNCTION chunks_set_tsv() RETURNS trigger AS $$
        BEGIN
            NEW.text_tsv = to_tsvector('simple', NEW.text);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute("DROP TRIGGER IF EXISTS chunks_set_tsv_trigger ON chunks")
    op.execute(
        """
        CREATE TRIGGER chunks_set_tsv_trigger
            BEFORE INSERT OR UPDATE OF text ON chunks
            FOR EACH ROW EXECUTE FUNCTION chunks_set_tsv();
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunks",
        "text_tsv",
        existing_type=postgresql.TSVECTOR(),
        comment="全文检索向量,触发器自动维护。当前用 simple 配置(未做中文分词,技术债)",
        existing_comment="全文检索向量,触发器从 text_tokens 生成(不是从 text —— simple 配置不分中文词)",
        existing_nullable=True,
    )
    op.drop_column("chunks", "text_tokens")
    # ### end Alembic commands ###
