"""term df table for bm25

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-20 12:54:44.633874
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "term_df",
        sa.Column("term", sa.Text(), nullable=False),
        sa.Column("ndoc", sa.Integer(), nullable=False, comment="这个词出现在多少个父块里"),
        sa.PrimaryKeyConstraint("term"),
        comment="词频表(派生数据,可重建)。BM25 靠它挑出罕见词,只用罕见词查",
    )
    op.create_index("idx_term_df_ndoc", "term_df", ["ndoc"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_term_df_ndoc", table_name="term_df")
    op.drop_table("term_df")
    # ### end Alembic commands ###
