"""add user kb tables

Revision ID: 71b3156b0c2c
Revises: cb293b016ff0
Create Date: 2026-08-18 10:55:55.619995
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '71b3156b0c2c'
down_revision: str | None = 'cb293b016ff0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_doc_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='用户文档切块。检索走 Milvus,这里存正文'
    )
    op.create_index(op.f('ix_user_doc_chunks_chunk_id'), 'user_doc_chunks', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_user_doc_chunks_doc_id'), 'user_doc_chunks', ['doc_id'], unique=False)
    op.create_index(op.f('ix_user_doc_chunks_user_id'), 'user_doc_chunks', ['user_id'], unique=False)
    op.create_table('user_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('n_chunks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='用户知识库文档。一行 = 一次上传'
    )
    op.create_index('idx_user_docs_user_time', 'user_docs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_docs_created_at'), 'user_docs', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_docs_doc_id'), 'user_docs', ['doc_id'], unique=True)
    op.create_index(op.f('ix_user_docs_user_id'), 'user_docs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_docs_user_id'), table_name='user_docs')
    op.drop_index(op.f('ix_user_docs_doc_id'), table_name='user_docs')
    op.drop_index(op.f('ix_user_docs_created_at'), table_name='user_docs')
    op.drop_index('idx_user_docs_user_time', table_name='user_docs')
    op.drop_table('user_docs')
    op.drop_index(op.f('ix_user_doc_chunks_user_id'), table_name='user_doc_chunks')
    op.drop_index(op.f('ix_user_doc_chunks_doc_id'), table_name='user_doc_chunks')
    op.drop_index(op.f('ix_user_doc_chunks_chunk_id'), table_name='user_doc_chunks')
    op.drop_table('user_doc_chunks')
    # ### end Alembic commands ###
