models:
  - name: deepseek-v4-flash
    model: deepseek-v4-flash
    base_url: https://api.deepseek.com/v1
    api_key: $DEEPSEEK_API_KEY
    class: langchain_deepseek:ChatDeepSeek
  - name: deepseek-v4-pro
    model: deepseek-v4-pro
    base_url: https://api.deepseek.com/v1
    api_key: $DEEPSEEK_API_KEY
    class: langchain_deepseek:ChatDeepSeek