"""baseline: documents + chunks 两张表

表结构的【第一个版本】。以后每次改结构 = 新增一个 migration 文件,
串成 0001 → 0002 → … 的链条;数据库里的 alembic_version 表记着当前在哪一版。
这正是手写 CREATE TABLE IF NOT EXISTS 做不到的:那玩意儿遇到已存在的表直接跳过,
什么也不做 —— 想加个字段?它假装成功,你的库和别人的库悄悄不一样了。

autogenerate 生成后【手工补】的两样(它生不出来 —— 模板那句 "please adjust!" 不是客套):
  ① postgresql 的 import:它用了 postgresql.TSVECTOR() 却没生成对应 import,是它的老毛病
  ② 触发器:Alembic 只 diff【表结构】,数据库里的函数/触发器它不管

注释(COMMENT ON)不在这里手写 —— 写在 models.py 的 comment= 上让 autogenerate 生成。
写在这里会造成模型和库【漂移】:模型没声明注释 → alembic check 判定该把注释删掉。
(踩过,正是 alembic check 抓出来的 —— 这就是为什么 CI 里要跑这条命令)

Revision ID: 0001
Revises:
Create Date: 2026-07-16
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # 手工补:autogenerate 漏掉的 import

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column(
            "document_id",
            sa.String(length=16),
            nullable=False,
            comment="内容寻址 ID = sha256 前16位。同内容永远同 ID → 幂等、天然去重",
        ),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("file_type", sa.String(length=16), nullable=False),
        sa.Column(
            "source",
            sa.String(length=32),
            nullable=False,
            comment="来源类别:期刊论文 / 标准规范",
        ),
        sa.Column(
            "parser",
            sa.String(length=32),
            nullable=False,
            comment="数据血缘:这篇是谁解析的(mineru/text)。换解析器后能定位受影响的数据",
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("doi", sa.Text(), nullable=True),
        sa.Column(
            "keywords",
            sa.ARRAY(sa.Text()),
            nullable=True,
            comment="PG 原生数组,支持 keywords @> ARRAY['PBAT'] 精确匹配",
        ),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("document_id"),
        sa.UniqueConstraint("sha256"),
        comment="文档元数据。一行 = 一篇论文/标准",
    )
    op.create_index(
        "idx_documents_keywords",
        "documents",
        ["keywords"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_documents_source", "documents", ["source"], unique=False)
    op.create_index("idx_documents_year", "documents", ["year"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("chunk_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=16), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column(
            "kind",
            sa.String(length=8),
            nullable=False,
            comment="parent=完整章节(给 LLM 看) / child=细粒度片段(拿去 embedding)",
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "section_path",
            sa.ARRAY(sa.Text()),
            nullable=True,
            comment="从文档根到本块的标题路径,如 {结果与讨论, 降解率}。栈算法重建章节树得到",
        ),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("element_type", sa.String(length=16), nullable=True),
        sa.Column(
            "text_tsv",
            postgresql.TSVECTOR(),
            nullable=True,
            comment="全文检索向量,触发器自动维护。当前用 simple 配置(未做中文分词,技术债)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'parent' AND parent_id IS NULL) OR (kind = 'child' AND parent_id IS NOT NULL)",
            name="chunks_parent_rule",
        ),
        sa.CheckConstraint("kind IN ('parent', 'child')", name="chunks_kind_check"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.document_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["chunks.chunk_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
        comment="检索单元。父块子块同表,靠 kind 区分:子块进 Milvus 做向量检索,命中后返回父块给 LLM(Small-to-Big)",
    )
    op.create_index("idx_chunks_document", "chunks", ["document_id"], unique=False)
    op.create_index("idx_chunks_kind", "chunks", ["kind"], unique=False)
    op.create_index("idx_chunks_parent", "chunks", ["parent_id"], unique=False)
    op.create_index(
        "idx_chunks_text_tsv",
        "chunks",
        ["text_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###

    # ══════════ 以下为手工补充(Alembic 不管触发器)══════════

    # ① updated_at 自动更新触发器
    #
    # 为什么必须在【数据库】做,而不是在 Python 里写 doc.updated_at = now():
    #   写库的路径有很多条(管道、修数据的脚本、DBA 手工 UPDATE、以后的 Web 后台)。
    #   靠每条路径自觉赋值 = 迟早有人忘,而且忘了【不报错】,数据只是悄悄不对。
    #   触发器在数据库层,任何路径的 UPDATE 都躲不掉。
    #   和 CHECK 约束、和 schema.py 的 @field_validator 是同一个思想:
    #   把不变量放在【数据最后必经的那一层】,而不是指望调用方守规矩。
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER documents_set_updated_at
            BEFORE UPDATE ON documents
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )

    # ② text_tsv 自动维护触发器(为 BM25 混合检索铺路)
    #
    # tsvector = PG 预先把文本切成词 + 记住词的位置,存成一列。
    # 查询时走 GIN 索引直接查它,不用扫全表。
    #
    # ⚠ 'simple' 配置 = 只按空格/标点切,【不做中文分词】。
    #   中文没空格 → "地膜降解性能好" 会被当成一整个词 → 搜 "降解" 搜不到。
    #   正解是装 zhparser / pg_jieba 扩展(要改 Docker 镜像,重建索引)。
    #   先用 simple 打地基:英文术语(PBAT/PLA/ASTM)和数字型号已经能精确匹配,
    #   而那恰好是纯向量检索最容易搞错的地方(实测:问 PBAT 命中了 PLA,0.502 vs 0.477)。
    #   中文分词是【明确的技术债】,等做 BM25 评测拿到数据再补 —— 别凭感觉提前优化。
    op.execute(
        """
        CREATE OR REPLACE FUNCTION chunks_set_tsv() RETURNS trigger AS $$
        BEGIN
            NEW.text_tsv = to_tsvector('simple', NEW.text);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER chunks_set_tsv_trigger
            BEFORE INSERT OR UPDATE OF text ON chunks
            FOR EACH ROW EXECUTE FUNCTION chunks_set_tsv();
        """
    )


def downgrade() -> None:
    # 手工补:先拆触发器和函数,再拆表 —— downgrade 必须是 upgrade 的严格逆序
    op.execute("DROP TRIGGER IF EXISTS chunks_set_tsv_trigger ON chunks")
    op.execute("DROP TRIGGER IF EXISTS documents_set_updated_at ON documents")
    op.execute("DROP FUNCTION IF EXISTS chunks_set_tsv()")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_chunks_text_tsv", table_name="chunks", postgresql_using="gin")
    op.drop_index("idx_chunks_parent", table_name="chunks")
    op.drop_index("idx_chunks_kind", table_name="chunks")
    op.drop_index("idx_chunks_document", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("idx_documents_year", table_name="documents")
    op.drop_index("idx_documents_source", table_name="documents")
    op.drop_index(
        "idx_documents_keywords", table_name="documents", postgresql_using="gin"
    )
    op.drop_table("documents")
    # ### end Alembic commands ###
